document.write('<table cellspacing="0" cellpadding="0" width="100%" border="0">');
document.write('<tr>');
document.write('<td bgcolor="#e7e7e7" width=160 valign="top" class="menubar">');
document.write('<a href="index.html"><font size=+1>EM/CL Home</font></a>');
document.write('<br><hr>');
document.write('<a href="unit1.html">unit 1</a>: Introduction');
document.write('<br>');
document.write('&emsp;<a href="exercise1.html">exercise 1</a>');
document.write('<br>');
document.write('<a href="unit2.html">unit 2</a>: Variables');
document.write('<br>');
document.write('&emsp;<a href="exercise2.html">exercise 2</a>');
document.write('<br>');
document.write('<a href="unit3.html">unit 3</a>: Flow control');
document.write('<br>');
document.write('&emsp;<a href="exercise3.html">exercise 3</a>');
document.write('<br>');
document.write('<a href="unit4.html">unit 4</a>: Loops');
document.write('<br>');
document.write('&emsp;<a href="exercise4.html">exercise 4</a>');
document.write('<br>');
document.write('<a href="unit5.html">unit 5</a>: Functions');
document.write('<br>');
document.write('&emsp;<a href="exercise5.html">exercise 5</a>');
document.write('<br>');
document.write('<a href="unit6.html">unit 6</a>: Datastructures');
document.write('<br>');
document.write('&emsp;<a href="exercise6.html">exercise 6</a>');
document.write('<br>');
document.write('<a href="unit7.html">unit 7</a>: Plotting');
document.write('<br>');
document.write('&emsp;<a href="exercise7.html">exercise 7</a>');
document.write('<br>');
document.write('<a href="unit8.html">unit 8</a>: I/O');
document.write('<br>');
document.write('&emsp;<a href="exercise8.html">exercise 8</a>');
document.write('<br>');
document.write('<a href="unit9.html">unit 9</a>: Algorithms');
document.write('<br>');
document.write('&emsp;<a href="exercise9.html">exercise 9</a>');
document.write('<br>');
document.write('<a href="unit10.html">unit 10</a>: Debugging');
document.write('<br>');
document.write('&emsp;<a href="exercise10.html">exercise 10</a>');
document.write('<br>');
document.write('<a href="unit11.html">unit 11</a>: Summary');
document.write('<br>');
document.write('&emsp;<a href="exercise11.html">exercise 11</a>');
document.write('<br>');
document.write('<hr>');
//document.write('<a href="exerciseX1.html">Exercise X1</a><br>');
//document.write('<a href="exerciseX2.html">Exercise X2</a><br>');
document.write('</td>');
document.write('<td width=10></td><td valign="top">');
